server:
  port: 8084
spring:
  application:
    name: geteway-server
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）   简单尝试
        - id: route_simple
          # 目标服务地址（uri：地址，请求转发后的地址）
#          uri: http://127.0.0.1:8082
          uri: lb://consumer-server
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            ## 转发地址格式为 uri/archive
            - Path=/api/test/**
          filters:
            #添加前缀
            #- PrefixPath=/test
            - StripPrefix=1
            - MyParam=name
      #默认过滤器会对所有的路由都生效
#      default-filters:
#        - AddResponseHeader=X-Response-Default-MyName, itcast
    corsConfigurations:
      '[/**]':
        allowedOrigins:
         - "http://docs.spring.io"
        allowedMethods:
         - GET

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka #注册到Eureka的地址
  instance:
    #s不使用IP地址
    prefer-ip-address: false
    #ip地址
    ip-address: 127.0.0.1
    #续约间隔时间
    lease-renewal-interval-in-seconds: 30
    #服务时效时间
    lease-expiration-duration-in-seconds: 90
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 10000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      circuitBreaker:
        errorThresholdPercentage: 50 # 触发熔断错误比例阈值，默认值50%      
        sleepWindowInMilliseconds: 10000 # 熔断后休眠时长，默认值5秒      
        requestVolumeThreshold: 10 # 熔断触发小请求次数，默认值是20
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000 #断路器超时时间，默认1000ms