server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka #注册到Eureka的地址
  instance:
    #s不使用IP地址
    prefer-ip-address: false
    #ip地址
    ip-address: 127.0.0.1
    #续约间隔时间
    lease-renewal-interval-in-seconds: 30
    #服务时效时间
    lease-expiration-duration-in-seconds: 90
zuul:
#  routes:
#    consumer-server:
#      path: /test/**
#      serviceId: consumer-server
#      strip-prefix: false
#  ignored-services:
#    - provider-server
  prefix: /api

spring:
  application:
    name: zuul-server

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 10000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      circuitBreaker:
        errorThresholdPercentage: 50 # 触发熔断错误比例阈值，默认值50%      
        sleepWindowInMilliseconds: 10000 # 熔断后休眠时长，默认值5秒      
        requestVolumeThreshold: 10 # 熔断触发小请求次数，默认值是20
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms